In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df =pd.read_csv('train.csv')

In [4]:
df

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0
...,...,...,...,...,...,...
404285,404285,433578,379845,How many keywords are there in the Racket prog...,How many keywords are there in PERL Programmin...,0
404286,404286,18840,155606,Do you believe there is life after death?,Is it true that there is life after death?,1
404287,404287,537928,537929,What is one coin?,What's this coin?,0
404288,404288,537930,537931,What is the approx annual cost of living while...,I am having little hairfall problem but I want...,0
404289,404289,537932,537933,What is like to have sex with cousin?,What is it like to have sex with your cousin?,0

In [5]:
df.sample

<bound method NDFrame.sample of             id    qid1    qid2  \
0            0       1       2
1            1       3       4
2            2       5       6
3            3       7       8
4            4       9      10
...        ...     ...     ...
404285  404285  433578  379845
404286  404286   18840  155606
404287  404287  537928  537929
404288  404288  537930  537931
404289  404289  537932  537933

                                                question1  \
0       What is the step by step guide to invest in sh...
1       What is the story of Kohinoor (Koh-i-Noor) Dia...
2       How can I increase the speed of my internet co...
3       Why am I mentally very lonely? How can I solve...
4       Which one dissolve in water quikly sugar, salt...
...                                                   ...
404285  How many keywords are there in the Racket prog...
404286          Do you believe there is life after death?
404287                                  What is one coin?
404288  What is the approx annual cost of living while...
404289              What is like to have sex with cousin?

                                                question2  is_duplicate
0       What is the step by step guide to invest in sh...             0
1       What would happen if the Indian government sto...             0
2       How can Internet speed be increased by hacking...             0
3       Find the remainder when [math]23^{24}[/math] i...             0
4                 Which fish would survive in salt water?             0
...                                                   ...           ...
404285  How many keywords are there in PERL Programmin...             0
404286         Is it true that there is life after death?             1
404287                                  What's this coin?             0
404288  I am having little hairfall problem but I want...             0
404289      What is it like to have sex with your cousin?             0

[404290 rows x 6 columns]>

In [6]:
df.shape

(404290, 6)

In [7]:
df.head()

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0

In [8]:
new_df = df.sample(30000)

In [9]:
new_df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [10]:
new_df.duplicated().sum()

np.int64(0)

In [11]:
ques_df = new_df[['question1','question2']]
ques_df.head()

,question1,question2
228043,"How do you say ""Austrian Army"" in Austrian Ger...","How do you say ""Austrian Government"" in Austri..."
386719,Which is safer for tourists: India or China?,"Which is safer for female tourists, the USA, C..."
355046,I feel lost. What do I do?,What are ways to stop feeling lost?
63981,Why is Spotify nott available in India?,Why is Spotify not available in India?
108488,What are the hardest things about being a foot...,What are the hardest things about being a foot...

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

# merge text
questions = list(ques_df['question1'])+ list(ques_df['question2'])

cv = CountVectorizer(max_features=3000)
q1_arr, q2_arr =np.vsplit(cv.fit_transform(questions).toarray(),2)

In [14]:
temp_df1 = pd.DataFrame(q1_arr, index= ques_df.index)
temp_df2 = pd.DataFrame(q2_arr, index= ques_df.index)
temp_df =pd.concat([temp_df1,temp_df2], axis =1)
temp_df.shape

(30000, 6000)

In [15]:
temp_df['is_duplicate'] = new_df['is_duplicate']
temp_df.head()

,0,1,2,3,4,5,6,7,8,9,...,2991,2992,2993,2994,2995,2996,2997,2998,2999,is_duplicate
228043,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
386719,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
355046,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
63981,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
108488,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(temp_df.iloc[:,0:-1].values,temp_df.iloc[:,-1].values,test_size=0.2,random_state=1)

In [20]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred = rf.predict(x_test)
accuracy_score(y_test,y_pred)

0.7375

In [21]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train,y_train)
y_pred = xgb.predict(X_test)
accuracy_score(y_test,y_pred)

0.7166666666666667